[package]
name = "nesemulib"
authors = ["Gordon Zhou gordonzhou223@gmail.com"]
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
bitflags = "2.5.0"

[dev-dependencies]
serde_json = "1.0"
